version: '3.1'

services:
  postgres:
    image: postgres
    container_name: 'pg_todo'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - todo_db:/var/lib/postgres

volumes:
  todo_db:
